const mod = process.env.mod || "";
const config = require(`../config/${mod}_config.json`);

const Embed = require(`../utilities/EmbedPaginator.js`)
const Utils = require(`../utilities/utilFuncs.js`)
const MsgUtils = require(`../utilities/messageUtils.js`)

const levelSchema = require(`../database/levelSchema.js`)
const dailyExpSchema = require(`../database/dailyExpSchema.js`)

function isLevelMessage(client, message)
{
	if (!message) return false;
	const author  = message.author.id == client.config.bots.avrae;
	const channel = ((message.channel.id == client.config.chan.xpSpam)||
	 				 (message.channel.id == client.config.chan.dmSpam)||
					 (message.channel.id == client.config.chan.retire));

	const content = (message && message.embeds && message.embeds.length > 0);
	return author && channel && content
}

async function logLevelMessage(client, message, interaction=null, sendResult=true)
{
	const updated = await updateDataFromMessage(client, message)
	return updated
}

/// Update the level embed
async function updateLevelMessage(channel) {
	const levelData = await findLevelData();
	const outputData = {};

	levelData.forEach( char =>
	{
		let key = char.name;
		let level = char.level;
		if (level <= 3) return;

		outputData[level] = outputData[level] ?? [];
		if (key.length > 25) key = key.substring(0, 22) + "...";
		outputData[level].push(key);		
	});

	const embed = new Embed()
		  embed.setTitle('Character Levels')
		  embed.setColor(0x00ff00)
		  embed.setFooter({text:'Procedurally generated by level up messages in #🌐💰-reward-and-loot-spam'});

	for (var [level, list] of Object.entries(outputData))
	{		
		list = list.sort();

		var listSize = 20;
		if (list.length <= 20)
			listSize = list.length
		else if (list.length <= 40)
			listSize = list.length / 2			
		if (listSize > 20)
			listSize = 20;
			
		var s = 1;
		var totalList = list.length;
		while (list.length > 0)
		{
			var subList = list.splice(0, listSize);
			var e = s + subList.length - 1;
			var r = s+"-"+e;
			if (totalList <= listSize)
				r = totalList;
			embed.addField("Level "+level+" ("+r+")", subList.join("\n"), true);
			s = e+1;
		}
	}

	await MsgUtils.channelCleanup(channel)
	embed.send(channel)
	return;
}

async function findLevelData(search)
{
	return await levelSchema.find(search)
}

async function getLevelData(search)
{
	//First try a basic find on the exact match
	const result = await levelSchema.findOne(search)
	if (result) return result;

	//If we didn't find a match there, see if we can do a less-precise match and return the first result
	if (search.name)
	{
		const newSearch = {name:search.name}
		const newResult = await levelSchema.find(newSearch)		
		return newResult[0] || null;
	}
	
	return null;
}

module.exports = {
	isLevelMessage,
	logLevelMessage,
	getLevelData,
	findLevelData,
	updateLevelMessage,
	PurgeUser,
	PurgeChar
}

async function updateLevelData(search, level, upsert = true)
{
	if (search.user == null)
		throw "levelUtils.updateLevelData: User is null"
	
	const timestamp = Date.now();
	const result = await levelSchema.findOneAndUpdate(
		search,
		{
			name: search.name,
			user: search.user,
			level: level,
			update: timestamp
		},
		{
			upsert: upsert
		})
	
	return result;
}

async function updateDataFromMessage(client, message)
{
	if (!isLevelMessage(client, message))
		return null;

	const config = client.config;
	const guild  = message.guild;
	const embed = message.embeds[0];
	const title = embed.title;
	const desc = embed.description;

	let data = [];
	let updateLevelMessage = false;

	//Parse data from the title
	if (title)
	{
		data.push(parseExpMessage(title));
		data.push(parseCurrentLevelMessage(title));
		data.push(parseLevelSummaryMessage(title, embed.fields));
		data.push(parseSetupMessage(title, embed.footer?.text));
		data.push(parseDMAwardMessage(title,desc));
		data.push(parseRetireMessage(title));
	}

	//Parse the Author
	if (embed.author)
		data.push(parseAuthor(guild, embed.author));

	//Look for the Next Level field
	data.push(parseNextLevelField(embed.fields));

	//Churn that into some final data
	var finalData = {};
	data.forEach(d=>{
		finalData = Object.assign(finalData, d);
	});
	if (finalData.hasOwnProperty('name') && finalData.name != "")
	{
		const query = {name: finalData.name, user: finalData.user}
		
		if (finalData.hasOwnProperty('delete'))
		{
			console.log("DELETE: ", finalData, "\n", query);
			if (query.name && query.user)
			{
				const oldRecord = await PurgeChar(query);	
				if (oldRecord)
				{
					await message.react("💀")			
					updateLevelMessage = true;
				}
				else
					await message.react("❓")
			}
		}
		else
		{
			console.log("UPDATE: ", finalData);

			const oldRecord = await updateLevelData(query, finalData.level);	
			await message.react(config.emoji.xp)

			console.log("PREVIOUS: ", oldRecord)
			updateLevelMessage = (!oldRecord || finalData.level != oldRecord.level)
			if (oldRecord && finalData.level != oldRecord.level)
				await message.react("🥳");			
		}
	}
	return updateLevelMessage;
}

function parseExpMessage(title)
{
	var pattern = "(.*) (?:gains|loses) ([0-9,]*) Experience";
		pattern+= "(?: and levels up to )?([0-9]+)?(?:..)?(?: level)?!";
	var regex = new RegExp(pattern,"gi");

	var data = {};
	var matches = [...title.matchAll(regex)];
	if (matches.length > 0)
	{
		data.name = matches[0][1];
		data.level = matches[0][3];
		console.log("Experience:", data);
	}
	return data;
}	
 
function parseCurrentLevelMessage(title)
{
	var pattern = "(.*) is currently ([0-9]+).. level!";
	var regex = new RegExp(pattern,"gi");

	var data = {};
	var matches = [...title.matchAll(regex)];
	if (matches.length > 0)
	{
		// console.log(matches);
		data.name = matches[0][1];
		data.level = parseInt(matches[0][2]);
		console.log("Level:", data);
	}
	return data;
}

function parseLevelSummaryMessage(title, fields)
{
	var pattern = "Level Summary for (.*):";
	var regex = new RegExp(pattern,"gi");

	var data = {};
	var matches = [...title.matchAll(regex)];
	if (matches.length > 0)
	{
		// console.log(matches);
		data.name = matches[0][1];
	}

	fields.forEach(field=>
	{
		if (field.name=="Total Level")
		{
			var value = field.value.replace(/[^\d]/g, "");
			data.level = parseInt(value);
			console.log("Level:", data);
		}
	});
	return data;
}

function parseSetupMessage(title, footer)
{
	var pattern = "Initial Setup for: (.*)";
	var regex = new RegExp(pattern,"gi");

	var data = {};
	var matches = [...title.matchAll(regex)];
	if (matches.length > 0)	
	{
		data.name = matches[0][1];
		console.log("Setup:", data);

		const [] = footer?.split("|")
	}
	return data;
}	

function parseDMAwardMessage(title,desc)
{
	var data = {};

	var tPattern = "(.*) gains .*"
	var tRegex = new RegExp(tPattern,"gi");
	var tMatches = [...title.matchAll(tRegex)];
	if (tMatches.length > 0)
		data.name = tMatches[0][1];

	var dPattern = "You advance to Level ([0-9]+)!"
	var dRegex = new RegExp(dPattern,"gi");	
	var dMatches = [...title.matchAll(dRegex)];
	if (dMatches.length > 0)
	{
		data.level = dMatches[0][1];
	}

	dPattern = "(.*) gains [0-9,xp]* \(([0-9,])xp total)"
	dRegex = new RegExp(dPattern,"gi");	
	dMatches = [...title.matchAll(dRegex)];
	if (dMatches.length > 0)
	{
		data.exp = dMatches[0][1];
	}

	if (data.level || data.exp)
		console.log("DM Award:", data);
	return data;
}

function parseRetireMessage(title)
{
	var pattern = "(.*) has (?:retired from adventuring|perished)...";
	var regex = new RegExp(pattern,"gi");

	var data = {};
	var matches = [...title.matchAll(regex)];
	if (matches.length > 0)
	{
		data.name = matches[0][1];
		data.delete = matches[0][1];
		console.log("Retire:", data);
	}
	return data;
}

function parseAuthor(guild, author)
{
	var data = {}
	var displayName = author.name.toLowerCase();
	let serverMembers = guild.members
	
	let matchedMember = serverMembers.cache.find(m => ((m.displayName.toLowerCase() === displayName) || 
													   (m.user.username.toLowerCase() === displayName)));
	if (matchedMember)
	{
		data.user = matchedMember.user.id;
		console.log("Author:", data);
	}
	return data;
}

function parseNextLevelField(fields)
{
	var data = {};
	fields.forEach(field=>
	{
		if (field.name=="Current Experience")
		{
			var value = field.value.replace(/[^\d]/g, "");
			data.exp = parseInt(value);
		}
		if (field.name.startsWith("Next Level: "))
		{
			var level = field.name.replace("Next Level: ","");
			data.level = parseInt(level) - 1;
		}
	});

	if (data.level || data.exp)
		console.log("Next Level:", data);
	return data;
}

async function PurgeChar(char)
{
	if (!char) return;
	let records = await levelSchema.findOneAndDelete(char);
	console.log("Chars",records)
	return records
}

async function PurgeUser(user)
{
	if (!user) return;
	const query = { user: user };
	let records = await levelSchema.deleteMany(query);
	console.log("Chars",records);
	records = await dailyExpSchema.deleteMany(query);
	console.log("Daily",records);	
}
